version: '3.9'

services:

  ui:
    build:
      context: .
      dockerfile: ./kgea/server/KGEA_UI_Dockerfile
    #environment:
    #  - SOME_ENV_VARIABLE=${SOME_ENV_VARIABLE:-default_value}
    ports:
    - "8090:8090"
    # depends_on:
    # - "archive"
    # volumes:
    # - $HOME/.aws:/root/.aws
    networks:
    - default

  archive:
    build:
      context: .
      dockerfile: ./kgea/server/KGEA_Archive_Dockerfile
    #environment:
    #  - SOME_ENV_VARIABLE=${SOME_ENV_VARIABLE:-default_value}
    ports:
    - "8080:8080"
    # depends_on:
    # - "kgx"
    volumes:
    - $HOME/.aws:/root/.aws
    networks:
    - default

  #  kgx:
  #    image: python:3.9
  #    environment:
  #      - SOME_ENV_VARIABLE=${SOME_ENV_VARIABLE:-default_value}
  #    ports:
  #      - "8100:8080"
  #    volumes:
  #      - $HOME/data:/data
  #      - $HOME/logs:/logs
  #    networks:
  #        - default

  memcached:
      image: memcached:latest
      ports:
        - "11211:11211"

networks:
    default:
        driver: bridge