version: '3'

services:
  kge_server:
    build: ./kgea/server
    #environment:
    #  - SOME_ENV_VARIABLE=${SOME_ENV_VARIABLE:-default_value}
    ports:
      - "8080:8080"
#    depends_on:
#      - "kgx"
    networks:
        - default

#  kgx:
#    image: python:3.9
#    environment:
#      - SOME_ENV_VARIABLE=${SOME_ENV_VARIABLE:-default_value}
#    ports:
#      - "8090:8080"
#    volumes:
#      - $HOME/data:/data
#      - $HOME/logs:/logs
#    networks:
#        - default

networks:
    default:
        driver: bridge