version: '3.9'

services:

  ui:
    build:
      context: .
      dockerfile: ./kgea/server/KGEA_UI_Dockerfile
    #    environment:
    #      # TODO: the need for explicit AWS credentials should be removed AWS IAM Roles are fully used
    #      - AWS_ACCESS_KEY_ID
    #      - AWS_SECRET_ACCESS_KEY
    #      - REGION_NAME=${REGION_NAME:-us-east-1}
    ports:
    - "8090:8090"
    # depends_on:
    # - "archive"
    volumes:
    - $HOME/.aws:/root/.aws
    networks:
    - default

  archive:
    build:
      context: .
      dockerfile: ./kgea/server/KGEA_Archive_Dockerfile
    #    environment:
    #      # TODO: the need for explicit AWS credentials will be removed AWS IAM Roles are fully used
    #      - AWS_ACCESS_KEY_ID
    #      - AWS_SECRET_ACCESS_KEY
    #      - REGION_NAME=${REGION_NAME:-us-east-1}
    ports:
    - "8080:8080"
    # depends_on:
    # - "kgx"
    volumes:
    - $HOME/.aws:/root/.aws
    networks:
    - default

  memcached:
      image: memcached:latest
      ports:
        - "11211:11211"

networks:
    default:
        driver: bridge