version: '3.9'

services:

  ui:
    build:
      context: .
      dockerfile: ./kgea/server/KGEA_UI_Dockerfile
    ports:
    - "8090:8090"
    networks:
    - default

  web_server:
    build:
      context: .
      dockerfile: ./kgea/server/KGEA_Web_Server_Dockerfile
    ports:
    - "8080:8080"
    networks:
    - default

  archiver:
    build:
      context: .
      dockerfile: ./kgea/server/KGEA_Archiver_Dockerfile
    ports:
      - "8100:8100"
    networks:
    - default

  memcached:
      image: memcached:latest
      ports:
        - "11211:11211"

networks:
    default:
        driver: bridge