# coding: utf-8

from kgea.server.web_services.models.base_model_ import Model
from kgea.server.web_services.models.kge_file_set_metadata import KgeFileSetMetadata
from kgea.server.web_services.models.kge_provider_metadata import KgeProviderMetadata
from kgea.server.web_services import util


class KgeMetadata(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, provider: KgeProviderMetadata=None, fileset: KgeFileSetMetadata=None):
        """KgeMetadata - a model defined in OpenAPI

        :param provider: The provider of this KgeMetadata.
        :param fileset: The fileset of this KgeMetadata.
        """
        self.openapi_types = {
            'provider': KgeProviderMetadata,
            'fileset': KgeFileSetMetadata
        }

        self.attribute_map = {
            'provider': 'provider',
            'fileset': 'fileset'
        }

        self._provider = provider
        self._fileset = fileset

    @classmethod
    def from_dict(cls, dikt: dict) -> 'KgeMetadata':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The KgeMetadata of this KgeMetadata.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def provider(self):
        """Gets the provider of this KgeMetadata.


        :return: The provider of this KgeMetadata.
        :rtype: KgeProviderMetadata
        """
        return self._provider

    @provider.setter
    def provider(self, provider):
        """Sets the provider of this KgeMetadata.


        :param provider: The provider of this KgeMetadata.
        :type provider: KgeProviderMetadata
        """

        self._provider = provider

    @property
    def fileset(self):
        """Gets the fileset of this KgeMetadata.


        :return: The fileset of this KgeMetadata.
        :rtype: KgeFileSetMetadata
        """
        return self._fileset

    @fileset.setter
    def fileset(self, fileset):
        """Sets the fileset of this KgeMetadata.


        :param fileset: The fileset of this KgeMetadata.
        :type fileset: KgeFileSetMetadata
        """

        self._fileset = fileset
