# coding: utf-8

from kgea.server.web_services.models.base_model_ import Model
from kgea.server.web_services import util


class KgxCompliance(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    ASSESSING = "Assessing"
    COMPLIANT = "Compliant"
    NON_COMPLIANT = "Non-Compliant"

    def __init__(self):
        """KgxCompliance - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt: dict) -> 'KgxCompliance':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The KgxCompliance of this KgxCompliance.
        """
        return util.deserialize_model(dikt, cls)
