# coding: utf-8

from kgea.server.archiver.models.base_model_ import Model
from kgea.server.archiver import util


class ProcessStatusCode(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    ONGOING = "Ongoing"
    COMPLETED = "Completed"
    ERROR = "Error"

    def __init__(self):
        """ProcessStatusCode - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt: dict) -> 'ProcessStatusCode':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The ProcessStatusCode of this ProcessStatusCode.
        """
        return util.deserialize_model(dikt, cls)
