# coding: utf-8

from kgea.server.archiver.models.base_model_ import Model
from kgea.server.archiver.models.process_status_code import ProcessStatusCode
from kgea.server.archiver import util


class StatusToken(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, status_token: str=None, kg_id: str=None, fileset_version: str=None, status: ProcessStatusCode=None):
        """StatusToken - a model defined in OpenAPI

        :param status_token: The status_token of this StatusToken.
        :param kg_id: The kg_id of this StatusToken.
        :param fileset_version: The fileset_version of this StatusToken.
        :param status: The status of this StatusToken.
        """
        self.openapi_types = {
            'status_token': str,
            'kg_id': str,
            'fileset_version': str,
            'status': ProcessStatusCode
        }

        self.attribute_map = {
            'status_token': 'status_token',
            'kg_id': 'kg_id',
            'fileset_version': 'fileset_version',
            'status': 'status'
        }

        self._status_token = status_token
        self._kg_id = kg_id
        self._fileset_version = fileset_version
        self._status = status

    @classmethod
    def from_dict(cls, dikt: dict) -> 'StatusToken':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The StatusToken of this StatusToken.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def status_token(self):
        """Gets the status_token of this StatusToken.

        Token tracking the status of post-processing of a KGE File Set.

        :return: The status_token of this StatusToken.
        :rtype: str
        """
        return self._status_token

    @status_token.setter
    def status_token(self, status_token):
        """Sets the status_token of this StatusToken.

        Token tracking the status of post-processing of a KGE File Set.

        :param status_token: The status_token of this StatusToken.
        :type status_token: str
        """
        if status_token is None:
            raise ValueError("Invalid value for `status_token`, must not be `None`")

        self._status_token = status_token

    @property
    def kg_id(self):
        """Gets the kg_id of this StatusToken.

        Knowledge Graph identifier of the KGE File Set being processed.

        :return: The kg_id of this StatusToken.
        :rtype: str
        """
        return self._kg_id

    @kg_id.setter
    def kg_id(self, kg_id):
        """Sets the kg_id of this StatusToken.

        Knowledge Graph identifier of the KGE File Set being processed.

        :param kg_id: The kg_id of this StatusToken.
        :type kg_id: str
        """
        if kg_id is None:
            raise ValueError("Invalid value for `kg_id`, must not be `None`")

        self._kg_id = kg_id

    @property
    def fileset_version(self):
        """Gets the fileset_version of this StatusToken.

        Semantic versioning of the version of the KGX File Set being processed.

        :return: The fileset_version of this StatusToken.
        :rtype: str
        """
        return self._fileset_version

    @fileset_version.setter
    def fileset_version(self, fileset_version):
        """Sets the fileset_version of this StatusToken.

        Semantic versioning of the version of the KGX File Set being processed.

        :param fileset_version: The fileset_version of this StatusToken.
        :type fileset_version: str
        """
        if fileset_version is None:
            raise ValueError("Invalid value for `fileset_version`, must not be `None`")

        self._fileset_version = fileset_version

    @property
    def status(self):
        """Gets the status of this StatusToken.


        :return: The status of this StatusToken.
        :rtype: ProcessStatusCode
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this StatusToken.


        :param status: The status of this StatusToken.
        :type status: ProcessStatusCode
        """
        if status is None:
            raise ValueError("Invalid value for `status`, must not be `None`")

        self._status = status
