openapi: 3.0.1
info:
  version: 0.0.1-dev
  title: >-
    (Template for) Knowledge Graph EXchange (KGE) File Set SmartAPI Entry
  description: >-
    (Template for) SmartAPI Entry for a distinct
    NCATS Biomedical Translator
    Knowledge Graph EXchange (KGE) File Set
  license:
    name: MIT 2.0
    url: https://en.wikipedia.org/wiki/MIT_License
  termsOfService: https://ncats.nih.gov/translator
  contact:
    name: {{nameOfSomebody}}
    x-role: responsible curator
    email: {{email4somebody}}
    x-id: https://github.com/{{gitId4somebody}}
  x-translator:
        component: KP # could sometimes be ARA or SRI Service or ???
        team:
        - {{nameOfTeam}}
servers:
  # $kg_name should be set to the
  # registered Knowledge Graph name in the KGE Archive
  - url: "_https://kge.starinformatics.ca/{{kgname}}"
    description: "Production Server"
externalDocs:
  description: >-
    Documentation for the NCATS Biomedical Translator
    Knowledge Graph Exchange (KGE) Archive
  url: https://github.com/NCATSTranslator/Knowledge_Graph_Exchange_Registry
tags:
  - name: translator
  - name: provider
    description: Provider metadata for KGX-formatted data files
    externalDocs:
      description: Documentation relating to KGX-formatted data file access
  - name: content
    description: Content metadata for KGX-formatted data files
    externalDocs:
      description: >-
        Documentation of Knowledge Graph Exchange content metadata
paths:
  /access:
    get:
      tags:
        - provider
      summary: Get KGE File Sets
      parameters:
        - name: kg_name
          in: path
          description: >-
            Name label of KGE File Set whose files are being accessed
          required: true
          # x-valueType:
          #  - don't know if this needs a SmartAPI value type?
          schema:
            type: string
      responses:
        '200':
          description: >-
            Name label of KGE File Set whose
            provider metadata is being reported
          content:
            application/json:
              schema:
                description: >-
                  Provider metadata describing the
                  location and inventory of KGE files
                type: object
                additionalProperties:
                  description: >-
                     Provider metadata attributes
                  $ref: '#/components/schemas/Attribute'
  /knowledge_map:
    get:
      tags:
        - content
      summary: Get supported relationships by source and target
      parameters:
        - name: kg_name
          in: path
          description: >-
            Name label of KGE File Set whose
            knowledge graph content metadata is being reported
          required: true
          # x-valueType:
          #  - don't know if this needs a SmartAPI value type?
          schema:
            type: string
      responses:
        '200':
          description: Predicates by source and target
          content:
            application/json:
              schema:
                description: Source map
                type: object
                additionalProperties:
                  description: Target map
                  type: object
                  additionalProperties:
                    description: Array of predicates
                    type: array
                    items:
                      type: string
                example:
                  'biolink:ChemicalSubstance':
                    'biolink:Gene':
                      - biolink:directly_interacts_with
                      - biolink:decreases_activity_of
components:
  schemas:
    Attribute:
      type: object
      description: Generic metadata attribute.
      properties:
        type:
          type: string
          description: >-
            Type of the metadata attribute, from the Translator Registry metadata dictionary.
          example: Foo
        value:
          description: >-
            Value of the attribute. May be any data type, including a list.
          example: bar
    required:
        - type
        - value
      additionalProperties: false
