openapi: 3.0.1
info:
  version: 1.0.0
  title: >-
    ${kg_name} Knowledge Graph eXchange File Set.
  description: >-
    ${kg_description}
  license:
    name: "${license_name}"
    url:  "${license_url}"
  termsOfService: "${terms_of_service}"
  contact:
    name: "${submitter_name}"
    x-role: "Submitter"
    email: "${submitter_email}"
  x-translator:
    component: "${translator_component}"
    team:
    - "${translator_team}"
  x-kge:
    id: "${kg_id}"
    name:  "${kg_name}"
servers:
  - url: "${host}/api/${kg_id}"
    description: "KGE Archive Entry base url for ${kg_name}"
externalDocs:
  description: >-
    Documentation for the NCATS Biomedical Translator
    Knowledge Graph Exchange (KGE) Archive
  url: https://github.com/NCATSTranslator/Knowledge_Graph_Exchange_Registry
tags:
  - name: translator
    description: Designates a NCATS Biomedical Data Translator component API
  - name: kge
    description: Designates a Translator Knowledge Graph eXchange (KGE) Archive API
  - name: content
    description: Endpoints to access version specific KGE file set content (meta-)data.
paths:
  /{kg_version}/meta_knowledge_graph:
    get:
      parameters:
        - name: fileset_version
          in: path
          description: >-
            Version of KGE File Set for a given knowledge graph.
          required: true
          schema:
            type: string
      tags:
        - content
      summary: Meta knowledge graph representation of this KGX knowledge graph.
      operationId: metaKnowledgeGraph
      responses:
        '200':
          description: >-
            Returns meta knowledge graph representation
            of this KGX knowledge graph.
          content:
            application/json:
              schema:
                $$ref: '#/components/schemas/MetaKnowledgeGraph'
        '404':
          description: >-
            KGE File Set was not found.
          content:
            application/json:
              schema:
                type: string
        '400':
          description: >-
            Bad request. The request is invalid according to this OpenAPI
            schema OR KGX knowledge graph identifier is not just unrecognized.
          content:
            application/json:
              schema:
                type: string
/{kg_version}/download:
    get:
      parameters:
        - name: fileset_version
          in: path
          description: >-
            Version of KGE File Set of the knowledge graph being accessed.
          required: true
          schema:
            type: string
      tags:
        - content
      summary: Returns specified KGE File Set as a gzip compressed tar archive
      operationId: downloadFileSet
      responses:
        '200':
          description: >-
            A KGE File Set as a gzip compressed tar archive of
            KGX compliant files plus an associated metadata json file
          content:
            application/gzip:
              schema:
                type: string
                format: binary
        '404':
          description: >-
            KGE File Set or its requested version was not found.
          content:
            application/json:
              schema:
                type: string
        '400':
          description: >-
            Bad request. Request is invalid according to this OpenAPI schema
          content:
            application/json:
              schema:
                type: string
components:
  schemas:
    BiolinkEntity:
      description: >-
        Compact URI (CURIE) for a Biolink class, biolink:NamedThing
        or a child thereof. The CURIE must use the prefix 'biolink:'
        followed by the PascalCase class name.
      type: string
      pattern: ^biolink:[A-Z][a-zA-Z]*$$
      externalDocs:
        description: Biolink model entities
        url: https://biolink.github.io/biolink-model/docs/NamedThing.html
      example: biolink:PhenotypicFeature
    BiolinkPredicate:
      description: >-
        CURIE for a Biolink 'predicate' slot, taken from the Biolink slot
        ('is_a') hierarchy rooted in biolink:related_to (snake_case). This
        predicate defines the Biolink relationship between the subject and
        object nodes of a biolink:Association defining a knowledge graph edge.
      type: string
      pattern: ^biolink:[a-z][a-z_]*$$
      externalDocs:
        description: Biolink model predicates
        url: https://biolink.github.io/biolink-model/docs/related_to.html
      example: biolink:interacts_with
    MetaKnowledgeGraph:
      type: object
      description: >-
        Knowledge-map representation of this TRAPI web service.
      properties:
        nodes:
          type: object
          description: >-
            Collection of node categories provided by this TRAPI web service,
            indexed by Biolink class CURIEs.
          additionalProperties:
            $$ref: '#/components/schemas/MetaNode'
        edges:
          type: array
          description: >-
            List of edges/predicates provided by this TRAPI web service.
          items:
            $$ref: '#/components/schemas/MetaEdge'
          minItems: 1
    MetaNode:
      type: object
      description: >-
        Description of a node category provided by this TRAPI web service.
      properties:
        id_prefixes:
          type: array
          description: >-
            List of CURIE prefixes for the node category that this TRAPI web
            service understands and accepts on the input.
          items:
            type: string
          minItems: 1
          example: [CHEMBL.COMPOUND, INCHIKEY]
        count:
          type: integer
          description: >-
            Total number of node instances of this node category known to this
            TRAPI web service, or -1 if the number is not known.
        count_by_source:
          type: object
          description: >-
            Number of node instances by their source
          additionalProperties:
            type: integer
          example:
            ChEMBL: 1234
      required:
        - id_prefixes
      additionalProperties: false
    MetaEdge:
      type: object
      description: >-
        Edge in a meta knowledge map describing relationship between a subject
        Biolink class and an object Biolink class.
      properties:
        subject:
          $$ref: '#/components/schemas/BiolinkEntity'
          description: >-
            Subject node category of this relationship edge.
          example: biolink:ChemicalSubstance
        predicate:
          $$ref: '#/components/schemas/BiolinkPredicate'
          description: >-
            Biolink relationship between the subject and object categories.
          example: biolink:affects
        object:
          $$ref: '#/components/schemas/BiolinkEntity'
          description: >-
            Object node category of this relationship edge.
          example: biolink:Protein
        relations:
          type: array
          description: >-
            Low-level relations from the underlying source.
          items:
            type: string
          example: [inhibits, activates]
        count:
          type: integer
          description: >-
            Total number of edge instances of this (subject, predicate,
            object) triple known to this TRAPI web service, or -1 if the
            number is not known.
        count_by_source:
          type: object
          description: >-
            Number of edge instances by their source.
          additionalProperties:
            type: integer
          example:
            ChEMBL: 1234
      required:
        - subject
        - predicate
        - object
      additionalProperties: false
