openapi: 3.0.1
info:
  version: 0.0.1-dev
  title: >-
    OpenAPI for the NCATS Biomedical Translator
    Knowledge Graph EXchange (KGE) Archive
  description: >-
    OpenAPI for the NCATS Biomedical Translator
    Knowledge Graph Exchange Archive
  license:
    name: MIT 2.0
    url: https://en.wikipedia.org/wiki/MIT_License
  termsOfService: https://ncats.nih.gov/translator
  contact:
    name: "Richard Bruskiewich"
    x-role: "responsible developer"
    email: "richard.bruskiewich@delphinai.com"
    x-id: "https://github.com/RichardBruskiewich"
  x-translator:
    component: "SRI service"
    team:
    - "SRI"
servers:
  - url: "http://localhost:8080/archive"
    description: "Localhost URL for server, to be proxied to the real internet"
externalDocs:
  description: >-
    Documentation for the NCATS Biomedical Translator
    Knowledge Graph Exchange (KGE) Archive
  url: "https://github.com/NCATSTranslator/Knowledge_Graph_Exchange_Registry"
tags:
  - name: upload
    description: KGE file set upload form
  - name: provider
    description: Provider metadata for KGE file set
  - name: content
    description: Content metadata for KGX-formatted data files in a KGE file set.
  - name: translator
paths:
  /register:
    post:
      tags:
        - upload
      summary: Register core parameters for the KGE File Set upload
      operationId: registerFileSet
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                submitter:
                  type: string
                kg_name:
                  type: string
              required:
                - submitter
                - kg_name
            encoding:
              submitter:
                contentType: text/plain; charset=utf-8
              kg_name:
                contentType: text/plain; charset=utf-8
      responses:
        '201':
          description: Upload successfully completed.
          content:
            application/json:
              schema:
                type: string
        '400':
          description: >-
            Bad request. The request is invalid according to this OpenAPI
            schema OR a specific parameter is believed to be invalid somehow
            (not just unrecognized).
          content:
            application/json:
              schema:
                type: string
        '500':
          description: >-
            Internal server error.
          content:
            application/json:
              schema:
                type: string
        '501':
          description: >-
            Not implemented.
          content:
            application/json:
              schema:
                type: string
  /upload:
    post:
      tags:
        - upload
      summary: Upload processing of KGE File Set file
      operationId: uploadFile
      requestBody:
        description: KGE File Set metadata or data file submitted
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              description: >-
                Uploading form posting of (meta-)data files. The 'upload_mode'
                string argument specifies the file type and/or mode as one of
                'metadata', 'content_from_local_file' or 'content_from_url'. If
                'metadata' or 'content_from_local_file' are indicated, then the
                'uploaded_file' parameter should be set to the file to be
                uploaded. If 'upload_mode' is set to 'content_from_url'
                then the 'content_url' parameter is taken as a REST endpoint
                of the file to be transferred into the Archive (authentication
                not yet supported - URL should provide unauthenticated access).
                The 'content_name' should be set either to the file name of
                the 'metadata' or 'content_from_local_file', or for url transfers,
                set by inference or as specified by the caller (especially if
                the 'content_url' doesn't resolve to a definitive file name).
              properties:
                kg_name:
                  type: string
                submitter:
                  type: string
                upload_mode:
                  type: string
                content_url:
                  type: string
                content_name:
                  type: string
                uploaded_file:
                  type: string
                  format: binary
              required:
              - kg_name
              - submitter
              - content_name
              - upload_mode
            encoding:
              kg_name:
                contentType: text/plain; charset=utf-8
              submitter:
                contentType: text/plain; charset=utf-8
              upload_mode:
                contentType: text/plain; charset=utf-8
              content_url:
                contentType: text/plain; charset=utf-8
              uploaded_file: # Property name (see above)
                contentType: text/csv, text/tab-separated-values, text/json
      responses:
        '201':
          description: Upload successfully completed.
          content:
            application/json:
              schema:
                type: string
        '400':
          description: >-
            Bad request. The request is invalid according to this OpenAPI
            schema OR a specific parameter is believed to be invalid somehow
            (not just unrecognized).
          content:
            application/json:
              schema:
                type: string
        '500':
          description: >-
            Internal server error.
          content:
            application/json:
              schema:
                type: string
        '501':
          description: >-
            Not implemented.
          content:
            application/json:
              schema:
                type: string
  /{kg_name}/access:
    get:
      parameters:
      - name: kg_name
        in: path
        description: >-
          Name label of KGE File Set, the knowledge graph
          for which data files are being accessed
        required: true
        schema:
          type: string
      tags:
        - provider
      summary: Get KGE File Sets
      operationId: access
      responses:
        '200':
          description: >-
            Name label of KGE File Set whose
            provider metadata is being reported
          content:
            application/json:
              schema:
                description: >-
                  Provider metadata describing the
                  location and inventory of KGE files
                type: object
                additionalProperties:
                  description: >-
                    Provider metadata attributes
                  $ref: '#/components/schemas/Attribute'
        '400':
          description: >-
            Bad request. The request is invalid according to this OpenAPI
            schema OR knowledge graph identifier is not just recognized.
          content:
            application/json:
              schema:
                type: string
  /{kg_name}/knowledge_map:
    get:
      parameters:
      - name: kg_name
        in: path
        description: >-
          Name label of KGE File Set, the knowledge graph
          for which content metadata is being accessed
        required: true
        schema:
          type: string
      tags:
        - content
      summary: Get supported relationships by source and target
      operationId: knowledgeMap
      responses:
        '200':
          description: Knowledge Map of predicates by source and target
          content:
            application/json:
              schema:
                description: Source map
                type: object
                additionalProperties:
                  description: Target map
                  type: object
                  additionalProperties:
                    description: Array of predicates
                    type: array
                    items:
                      type: string
                example:
                  'biolink:ChemicalSubstance':
                    'biolink:Gene':
                      - biolink:directly_interacts_with
                      - biolink:decreases_activity_of
        '400':
          description: >-
            Bad request. The request is invalid according to this OpenAPI
            schema OR knowledge graph identifier is not just unrecognized.
          content:
            application/json:
              schema:
                type: string
components:
  schemas:
    Attribute:
      type: object
      description: Generic metadata attribute.
      properties:
        type:
          type: string
          description: >-
            Type of the metadata attribute, from the Translator Registry metadata dictionary.
          example: "Foo"
        value:
          type: string
          description: >-
            Value of the attribute, encoded as a string.
          example: "Bar"
      required:
          - type
          - value
      additionalProperties: false
