openapi: 3.0.1
info:
  version: 0.0.1-dev
  title: >-
    OpenAPI for the NCATS Biomedical Translator
    Knowledge Graph EXchange (KGE) Archive
  description: >-
    OpenAPI for the NCATS Biomedical Translator
    Knowledge Graph Exchange Archive
  license:
    name: MIT 2.0
    url: https://en.wikipedia.org/wiki/MIT_License
  termsOfService: https://ncats.nih.gov/translator
  contact:
    name: "Richard Bruskiewich"
    x-role: "responsible developer"
    email: "richard.bruskiewich@delphinai.com"
    x-id: "https://github.com/RichardBruskiewich"
  x-translator:
    component: "SRI service"
    team:
    - "SRI"
servers:
  - url: "http://localhost:8080/kge-archive"
    description: "Localhost URL for server, to be proxied to the real internet"
externalDocs:
  description: >-
    Documentation for the NCATS Biomedical Translator
    Knowledge Graph Exchange (KGE) Archive
  url: "https://github.com/NCATSTranslator/Knowledge_Graph_Exchange_Registry"
tags:
  - name: upload
    description: KGE file set upload form
  - name: provider
    description: Provider metadata for KGE file set
  - name: content
    description: Content metadata for KGX-formatted data files in a KGE file set.
  - name: translator
paths:
  /form:
    get:
      tags:
        - upload
      summary: Get web form for specifying KGE File Set upload
      operationId: getUploadForm
      responses:
        '200':
          description: Returns a web form for uploading a KGE File Set
          content:
            text/html:
              schema:
                description: KGE File Set upload HTML web form
                type: string
  /register:
    post:
      tags:
        - upload
      summary: Register web form details specifying a KGE File Set location
      operationId: registerFileSet
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                submitter:
                  type: string
                kg_name:
                  type: string
              required:
                - submitter
                - kg_name
      responses:
        '201':
          description: Upload successfully completed.
          content:
            application/json:
              schema:
                type: string
        '400':
          description: >-
            Bad request. The request is invalid according to this OpenAPI
            schema OR a specific parameter is believed to be invalid somehow
            (not just unrecognized).
          content:
            application/json:
              schema:
                type: string
        '500':
          description: >-
            Internal server error.
          content:
            application/json:
              schema:
                type: string
        '501':
          description: >-
            Not implemented.
          content:
            application/json:
              schema:
                type: string
  /upload/{kg_name}:
    post:
      parameters:
        - name: kg_name
          in: path
          required: true
          schema:
            type: string
      tags:
        - upload
      summary: Upload web form details specifying a KGE File Set upload process
      operationId: uploadFileSet
      requestBody:
        description: KGE File Set metadata and data files submitted
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              description: "$ref: '#/components/schemas/KgeFileSet'"
              properties:
                data_file_content:
                  type: string
                  format: binary
                data_file_metadata:
                  type: string
                  format: binary
              required:
                - data_file_content
            encoding: # The same level as schema
              data_file_content: # Property name (see above)
                contentType: text/csv, text/tab-separated-values
      responses:
        '201':
          description: Upload successfully completed.
          content:
            application/json:
              schema:
                type: string
        '400':
          description: >-
            Bad request. The request is invalid according to this OpenAPI
            schema OR a specific parameter is believed to be invalid somehow
            (not just unrecognized).
          content:
            application/json:
              schema:
                type: string
        '500':
          description: >-
            Internal server error.
          content:
            application/json:
              schema:
                type: string
        '501':
          description: >-
            Not implemented.
          content:
            application/json:
              schema:
                type: string
  /{kg_name}/access:
    get:
      tags:
        - provider
      summary: Get KGE File Sets
      operationId: access
      parameters:
        - name: kg_name
          in: path
          description: >-
            Name label of KGE File Set whose files are being accessed
          required: true
          schema:
            type: string
      responses:
        '200':
          description: >-
            Name label of KGE File Set whose
            provider metadata is being reported
          content:
            application/json:
              schema:
                description: >-
                  Provider metadata describing the
                  location and inventory of KGE files
                type: object
                additionalProperties:
                  description: >-
                    Provider metadata attributes
                  $ref: '#/components/schemas/Attribute'
        '400':
          description: >-
            Bad request. The request is invalid according to this OpenAPI
            schema OR knowledge graph identifier is not just unrecognized.
          content:
            application/json:
              schema:
                type: string
  /{kg_name}/knowledge_map:
    get:
      tags:
        - content
      summary: Get supported relationships by source and target
      parameters:
        - name: kg_name
          in: path
          description: >-
            Name label of KGE File Set whose knowledge graph
            content metadata is being reported
          required: true
          schema:
            type: string
      operationId: knowledgeMap
      responses:
        '200':
          description: Knowledge Map of predicates by source and target
          content:
            application/json:
              schema:
                description: Source map
                type: object
                additionalProperties:
                  description: Target map
                  type: object
                  additionalProperties:
                    description: Array of predicates
                    type: array
                    items:
                      type: string
                example:
                  'biolink:ChemicalSubstance':
                    'biolink:Gene':
                      - biolink:directly_interacts_with
                      - biolink:decreases_activity_of
        '400':
          description: >-
            Bad request. The request is invalid according to this OpenAPI
            schema OR knowledge graph identifier is not just unrecognized.
          content:
            application/json:
              schema:
                type: string
components:
  schemas:
    KgeFileSet:
      description: >-
        Stub implementation of KGE File Set upload web form.
      type: object
      properties:
        submitter:
          type: string
        kg_name:
          type: string
        data_file_name:
          type: string
        metadata_file_name:
          type: string
      required:
        - submitter
        - kg_name
        - data_file_name

    Attribute:
      type: object
      description: Generic metadata attribute.
      properties:
        type:
          type: string
          description: >-
            Type of the metadata attribute, from the Translator Registry metadata dictionary.
          example: "Foo"
        value:
          type: string
          description: >-
            Value of the attribute, encoded as a string.
          example: "Bar"
      required:
          - type
          - value
      additionalProperties: false