openapi: 3.0.1
info:
  version: 1.0.0
  title: >-
    OpenAPI for the Biomedical Translator Knowledge Graph EXchange Archiver worker process
    which post-processes KGE File Sets which have been uploaded.
    Although this API is SmartAPI compliant, it will not normally be visible
    in the Translator SmartAPI Registry since it is mainly meant to be
    only accessed internally by the KGE Archiver back end.
  description: >-
    OpenAPI for the NCATS Biomedical Translator
    Knowledge Graph Exchange Archiver Post-Processor
  license:
    name: MIT 2.0
    url: https://en.wikipedia.org/wiki/MIT_License
  termsOfService: https://ncats.nih.gov/translator
  contact:
    name: "Richard Bruskiewich"
    x-role: "responsible developer"
    email: "richard.bruskiewich@delphinai.com"
    x-id: "https://github.com/RichardBruskiewich"
  x-translator:
    component: "SRI service"
    team:
    - "SRI"
servers:
  - url: "http://localhost:8100/archiver"
    description: "Localhost URL for server, to be proxied to the real internet"
externalDocs:
  description: >-
    Documentation for the NCATS Biomedical Translator
    Knowledge Graph Exchange (KGE) Archiver Post-Processor
  url: "https://github.com/NCATSTranslator/Knowledge_Graph_Exchange_Registry"
tags:
  - name: translator
    description: Designates a NCATS Biomedical Data Translator component API
  - name: kge
    description: Designates a Translator Knowledge Graph eXchange (KGE) Archive API
  - name: archiver
    description: Endpoints to access the post-processor archiver
paths:
  /process:
    post:
      description: >-
        Posts a KGE File Set for post-processing after upload.
      tags:
        - archiver
      summary: Posts a KGE File Set for post-processing after upload.
      operationId: process_fileset
      requestBody:
        $ref: '#/components/requestBodies/ProcessKgeFileSetBody'
      responses:
        '201':
          description:  >-
            Task to post-process new KGE File Set successfully submitted.
          content:
            application/json:
              schema:
                type: string
        '400':
          description: >-
            Bad request. Request is invalid according to this OpenAPI
            schema OR a specific parameter is believed to be invalid somehow
            (or not just recognized).
          content:
            application/json:
              schema:
                type: string
  /status:
    get:
      description: >-
        Poll the status of a given post-processing task.
      parameters:
        - name: process_token
          in: query
          description: >-
            Process token associated with a KGE File Set post-processing task.
          required: true
          schema:
            type: string
      tags:
        - archiver
      summary: Get the progress of post-processing of a KGE File Set.
      operationId: get_processing_status
      responses:
        '200':
          description: Details about the status of a KGE File Set post-processing operation.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusToken'
        '404':
          description: >-
            Specified upload token is unknown.
          content:
            application/json:
              schema:
                type: string
        '400':
          description: >-
            Bad request. Request is invalid according to this
            OpenAPI schema OR a specific parameter is believed
            to be invalid somehow (or just not recognized).
          content:
            application/json:
              schema:
                type: string
components:
  requestBodies:
    ProcessKgeFileSetBody:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/KgeFileSetMetadata'
      required: true
  schemas:
    KgeFileSetMetadata:
      description: >-
        Metadata including content metadata and the inventory of
        associated files, for a specific version of KGE File Set.
      type: object
      properties:
        kg_id:
          description: >-
            Knowledge Graph identifier.
          type: string
        fileset_version:
          description: >-
            Semantic versioning of the version of the KGX File Set of the given knowledge graph.
          type: string
          example: "1.0"
        date_stamp:
          description: >-
            Date stamp of the file set.
          type: string
          format: date
        submitter_name:
          description: >-
            Name of the submitter of the KGE FileSet
          type: string
          example: "John Smith"
        submitter_email:
          description: >-
            Email address for the submitter.
          type: string
          example: "jsmith@knowledge.org"
        biolink_model_release:
          description: >-
            Biolink Model released associated with the file set.
          type: string
          example: "2.5.0"
        status:
          $ref: '#/components/schemas/KgeFileSetStatusCode'
        files:
          description: >-
            Annotated list of files within a given file set.
          type: array
          items:
            $ref: '#/components/schemas/KgeFile'
        size:
          description: approximate aggregate size of data files in the file set (megabytes)
          type: number
          format: float
    KgeFileType:
      description: >-
        KGE File classifications.
      type: string
      enum:
        - UNKNOWN
        - CONTENT_METADATA_FILE
        - DATA_FILE
        - NODES
        - EDGES
        - ARCHIVE
      example: NODES
    KgeFile:
      description: >-
        Annotated file in a KGE File Set.
      type: object
      properties:
        file_type:
          description: >-
            Used to designate the type of file: mainly (content,
            provider or fileset) meta-, node or edge data.
          $ref: '#/components/schemas/KgeFileType'
        file_name:
          description: name of file
          type: string
        file_size:
          description: size of file in bytes
          type: integer
          example: 120000000
      required:
        - file_type
        - file_name
        - file_size
      additionalProperties: false
    StatusToken:
      description: >-
        Token tracking the status of post-processing of a KGE File Set.
      type: object
      properties:
        status_token:
          description: >-
            Token tracking the status of post-processing of a KGE File Set.
          type: string
        status:
          description: >-
            Code for status of post-processing of a KGE File Set.
          $ref: '#/components/schemas/ProcessStatusCode'
      required:
        - status_token
        - status
      additionalProperties: false
    ProcessStatusCode:
      description: >-
        Code for status of upload or direct URL
        transfer progress for a given file.
      type: string
      enum:
        - Ongoing
        - Completed
        - Error
    KgeFileSetStatusCode:
      description: >-
        Code for status of processing for a KGE File Set.
      type: string
      enum:
        - Created
        - Loaded
        - Processing
        - Validated
        - Error
      example: Validated
