# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.any_type import AnyType
from openapi_server import util

from openapi_server.models.any_type import AnyType  # noqa: E501

class Attribute(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, type=None, value=None):  # noqa: E501
        """Attribute - a model defined in OpenAPI

        :param type: The type of this Attribute.  # noqa: E501
        :type type: str
        :param value: The value of this Attribute.  # noqa: E501
        :type value: AnyType
        """
        self.openapi_types = {
            'type': str,
            'value': AnyType
        }

        self.attribute_map = {
            'type': 'type',
            'value': 'value'
        }

        self._type = type
        self._value = value

    @classmethod
    def from_dict(cls, dikt) -> 'Attribute':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Attribute of this Attribute.  # noqa: E501
        :rtype: Attribute
        """
        return util.deserialize_model(dikt, cls)

    @property
    def type(self):
        """Gets the type of this Attribute.

        Type of the metadata attribute, from the Translator Registry metadata dictionary.  # noqa: E501

        :return: The type of this Attribute.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this Attribute.

        Type of the metadata attribute, from the Translator Registry metadata dictionary.  # noqa: E501

        :param type: The type of this Attribute.
        :type type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def value(self):
        """Gets the value of this Attribute.

        Value of the attribute. May be any data type, including a list.  # noqa: E501

        :return: The value of this Attribute.
        :rtype: AnyType
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this Attribute.

        Value of the attribute. May be any data type, including a list.  # noqa: E501

        :param value: The value of this Attribute.
        :type value: AnyType
        """
        if value is None:
            raise ValueError("Invalid value for `value`, must not be `None`")  # noqa: E501

        self._value = value
