openapi: 3.0.1
info:
  contact:
    email: richard.bruskiewich@delphinai.com
    name: Richard Bruskiewich
    x-role: responsible developer
    x-id: https://github.com/RichardBruskiewich
  description: OpenAPI for the NCATS Biomedical Translator Knowledge Graph Exchange
    Archive
  license:
    name: MIT 2.0
    url: https://en.wikipedia.org/wiki/MIT_License
  termsOfService: https://ncats.nih.gov/translator
  title: OpenAPI for the NCATS Biomedical Translator Knowledge Graph EXchange (KGE)
    Archive
  version: 0.0.1-dev
  x-translator:
    component: SRI service
    team:
    - SRI
externalDocs:
  description: Documentation for the NCATS Biomedical Translator Knowledge Graph Exchange
    (KGE) Archive
  url: https://github.com/NCATSTranslator/Knowledge_Graph_Exchange_Registry
servers:
- description: Localhost URL for server, to be proxied to the real internet
  url: http://localhost:8080/archive
tags:
- description: KGE file set upload form
  name: upload
- description: Provider metadata for KGE file set
  name: provider
- description: Content metadata for KGX-formatted data files in a KGE file set.
  name: content
- name: translator
paths:
  /register:
    post:
      operationId: register_file_set
      requestBody:
        $ref: '#/components/requestBodies/inline_object'
        content:
          application/x-www-form-urlencoded:
            schema:
              properties:
                submitter:
                  type: string
                kg_name:
                  type: string
              required:
              - kg_name
              - submitter
              type: object
        required: true
        x-body-name: body
      responses:
        "201":
          content:
            application/json:
              schema:
                type: string
          description: Upload successfully completed.
        "400":
          content:
            application/json:
              schema:
                type: string
          description: Bad request. The request is invalid according to this OpenAPI
            schema OR a specific parameter is believed to be invalid somehow (not
            just unrecognized).
        "500":
          content:
            application/json:
              schema:
                type: string
          description: Internal server error.
        "501":
          content:
            application/json:
              schema:
                type: string
          description: Not implemented.
      summary: Register core parameters for the KGE File Set upload
      tags:
      - upload
      x-openapi-router-controller: openapi_server.controllers.upload_controller
      x-codegen-request-body-name: body
  /upload:
    post:
      operationId: upload_file
      requestBody:
        $ref: '#/components/requestBodies/inline_object_1'
        content:
          multipart/form-data:
            encoding:
              content_file:
                contentType: text/csv, text/tab-separated-values, text/json
                style: form
            schema:
              description: Uploading form posting of (meta-)data files. The 'upload_mode'
                string argument specifies the file type and/or mode as one of 'metadata',
                'content_from_local_file' or 'content_from_url'. If 'metadata' or
                'content_from_local_file' are indicated, then the 'uploaded_file'
                parameter should be set to the file to be uploaded. If 'upload_mode'
                is set to 'content_from_url' then the 'content_url' parameter is taken
                as a REST endpoint of the file to be transferred into the Archive
                (authentication not yet supported - URL should provide unauthenticated
                access)
              properties:
                upload_mode:
                  type: string
                content_url:
                  format: binary
                  type: string
                content_file:
                  format: binary
                  type: string
              required:
              - upload_mode
              type: object
        description: KGE File Set metadata or data file submitted
        required: true
        x-body-name: body
      responses:
        "201":
          content:
            application/json:
              schema:
                type: string
          description: Upload successfully completed.
        "400":
          content:
            application/json:
              schema:
                type: string
          description: Bad request. The request is invalid according to this OpenAPI
            schema OR a specific parameter is believed to be invalid somehow (not
            just unrecognized).
        "500":
          content:
            application/json:
              schema:
                type: string
          description: Internal server error.
        "501":
          content:
            application/json:
              schema:
                type: string
          description: Not implemented.
      summary: Upload processing of KGE File Set file
      tags:
      - upload
      x-openapi-router-controller: openapi_server.controllers.upload_controller
      x-codegen-request-body-name: body
  /{kg_name}/access:
    get:
      operationId: access
      parameters:
      - description: Name label of KGE File Set, the knowledge graph for which data
          files are being accessed
        explode: false
        in: path
        name: kg_name
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                additionalProperties:
                  $ref: '#/components/schemas/Attribute'
                description: Provider metadata describing the location and inventory
                  of KGE files
                type: object
          description: Name label of KGE File Set whose provider metadata is being
            reported
        "400":
          content:
            application/json:
              schema:
                type: string
          description: Bad request. The request is invalid according to this OpenAPI
            schema OR knowledge graph identifier is not just unrecognized.
      summary: Get KGE File Sets
      tags:
      - provider
      x-openapi-router-controller: openapi_server.controllers.provider_controller
  /{kg_name}/knowledge_map:
    get:
      operationId: knowledge_map
      parameters:
      - description: Name label of KGE File Set, the knowledge graph for which content
          metadata is being accessed
        explode: false
        in: path
        name: kg_name
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                additionalProperties:
                  additionalProperties:
                    description: Array of predicates
                    items:
                      type: string
                    type: array
                  description: Target map
                  type: object
                description: Source map
                example:
                  biolink:ChemicalSubstance:
                    biolink:Gene:
                    - biolink:directly_interacts_with
                    - biolink:decreases_activity_of
                type: object
          description: Knowledge Map of predicates by source and target
        "400":
          content:
            application/json:
              schema:
                type: string
          description: Bad request. The request is invalid according to this OpenAPI
            schema OR knowledge graph identifier is not just unrecognized.
      summary: Get supported relationships by source and target
      tags:
      - content
      x-openapi-router-controller: openapi_server.controllers.content_controller
components:
  requestBodies:
    inline_object_1:
      content:
        multipart/form-data:
          schema:
            $ref: '#/components/schemas/inline_object_1'
      required: true
    inline_object:
      content:
        application/x-www-form-urlencoded:
          schema:
            $ref: '#/components/schemas/inline_object'
      required: true
  schemas:
    Attribute:
      additionalProperties: false
      description: Generic metadata attribute.
      properties:
        type:
          description: Type of the metadata attribute, from the Translator Registry
            metadata dictionary.
          example: Foo
          type: string
        value:
          description: Value of the attribute, encoded as a string.
          example: Bar
          type: string
      required:
      - type
      - value
      type: object
    inline_object:
      properties:
        submitter:
          type: string
        kg_name:
          type: string
      required:
      - kg_name
      - submitter
      type: object
    inline_object_1:
      description: Uploading form posting of (meta-)data files. The 'upload_mode'
        string argument specifies the file type and/or mode as one of 'metadata',
        'content_from_local_file' or 'content_from_url'. If 'metadata' or 'content_from_local_file'
        are indicated, then the 'uploaded_file' parameter should be set to the file
        to be uploaded. If 'upload_mode' is set to 'content_from_url' then the 'content_url'
        parameter is taken as a REST endpoint of the file to be transferred into the
        Archive (authentication not yet supported - URL should provide unauthenticated
        access)
      properties:
        upload_mode:
          type: string
        content_url:
          format: binary
          type: string
        content_file:
          format: binary
          type: string
      required:
      - upload_mode
      type: object
