openapi: 3.0.1
info:
  description: >-
    OpenAPI for the NCATS Biomedical Translator
    Knowledge Graph Exchange Archive
  version: 0.0.1-dev
  title: >-
    OpenAPI for the NCATS Biomedical Translator
    Knowledge Graph EXchange (KGE) Archive
  contact:
    email: richard.bruskiewich@delphinai.com
  license:
    name: MIT 2.0
    url: https://en.wikipedia.org/wiki/MIT_License
  termsOfService: https://ncats.nih.gov/translator
externalDocs:
  description: >-
    Documentation for the NCATS Biomedical Translator
    Knowledge Graph Exchange (KGE) Archive
  url: https://github.com/NCATSTranslator/Knowledge_Graph_Exchange_Registry
tags:
  - name: metadata
    description: Get KGX metadata
    externalDocs:
      description: >-
        Documentation of Knowledge Graph Exchange content metadata
      url: http://kge.ncats.io/overview.html#metadata
  - name: access
    description: Access KGX-formatted data files
    externalDocs:
      description: Documentation relating to KGX-formatted data file access
      url: http://kge.ncats.io/overview.html#access
paths:
  /catalog:
    get:
      tags:
        - metadata
      summary: Get catalog of available knowledge graphs
        '200':
          description: >-
            Knowledge Graphs available by identifier, with metadata attributes
          content:
            application/json:
              schema:
                description: Catalog of knowledge graphs indexed by identifier
                type: object
                additionalProperties:
                  description: >-
                    Array of metadata describing a knowledge graph
                  type: array
                  items:
                    $ref: '#/components/schemas/Attribute'
                # This is a bit of a facetious example since not KGE metadata
                example:
                  'Some-KG-identifier':
                    - name: PubMed Identifier
                      value: 29146545
                      type: EDAM:data_1187
                      url: https://pubmed.ncbi.nlm.nih.gov/29146545
                      source: PMID
components:
  schemas:
    Attribute:
      type: object
      description: Generic attribute for a node
      properties:
        name:
          type: string
          description: >-
            Human-readable name or label for the attribute. Should be the name
            of the semantic type term.
          example: PubMed Identifier
        value:
          example: 29146545
          description: >-
            Value of the attribute. May be any data type, including a list.
        type:
          type: string
          description: >-
            CURIE of the semantic type of the attribute, from the EDAM ontology
            if possible. If a suitable identifier does not exist, enter a
            descriptive phrase here and submit the new type for consideration
            by the appropriate authority.
          example: EDAM:data_1187
        url:
          type: string
          description: >-
            Human-consumable URL to link out and read about the attribute (not
            the node).
          example: https://pubmed.ncbi.nlm.nih.gov/29146545
        source:
          type: string
          description: Source of the attribute, as a CURIE prefix.
          example: PMID
      required:
        - type
        - value
      additionalProperties: false
